# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  # last partition as boot, device = "/dev/sdb2";
  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/66F6-957D";
    fsType = "vfat";
  };

  # rootb: first partition ext4 as root
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/361434b5-c39b-4bf0-9fc0-956e8a4e5f5b";
    fsType = "ext4";
  };

  # swap file instead of a particular swapswapDevices
  fileSystems."/swap" = {
    device = "/dev/disk/by-uuid/bc51540f-f085-44a3-ad6c-46bf2e138f6b";
    fsType = "btrfs";
    options = ["subvol=@swap" "rw"];
  };
  # remount swapfile in read-write mode
  fileSystems."/swap/swapfile" = {
    # the swapfile is located in /swap subvolume, so we need to mount /swap first.
    depends = ["/swap"];
    device = "/swap/swapfile";
    fsType = "none";
    options = ["bind" "rw"];
  };
  swapDevices = [
    {device = "/swap/swapfile";}
    # {device = "/dev/disk/by-uuid/f033c305-e649-4599-aa05-ccf352da4121";}
  ];

  # persistent
  fileSystems."/persistent" = {
    device = "/dev/disk/by-uuid/bc51540f-f085-44a3-ad6c-46bf2e138f6b";
    fsType = "btrfs";
    options = ["subvol=@persistent" "noatime" "compress-force=zstd:1"];
    neededForBoot = true;
  };
  # guix
  fileSystems."/gnu" = {
    device = "/dev/disk/by-uuid/bc51540f-f085-44a3-ad6c-46bf2e138f6b";
    fsType = "btrfs";
    options = ["subvol=@guix" "noatime" "compress-force=zstd:1"];
  };

  # tmp, cleared at boot
  fileSystems."/tmp" = {
    device = "/dev/disk/by-uuid/bc51540f-f085-44a3-ad6c-46bf2e138f6b";
    fsType = "btrfs";
    options = ["subvol=@tmp" "noatime" "compress-force=zstd:1"];
  };

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
